# Generated by Django 4.2.6 on 2024-01-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='bio',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='client',
            name='img',
            field=models.ImageField(null=True, upload_to='static/images/proyects'),
        ),
        migrations.AlterField(
            model_name='client',
            name='job',
            field=models.CharField(default='', max_length=100),
        ),
    ]
