# Generated by Django 4.2.6 on 2024-01-25 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_proyecto_creador_alter_proyecto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='creador',
        ),
    ]
