# Generated by Django 4.2.6 on 2024-01-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_remove_proyecto_creador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='imagen',
            field=models.ImageField(upload_to='images/proyectos/'),
        ),
    ]
