# Generated by Django 4.2.6 on 2024-01-31 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_proyecto_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='usuario',
        ),
    ]
